#!/bin/bash

# Check if the BUILDKITE_S3_BUCKET environment variable is set
if [ -z "$BUILDKITE_DEPLOY_TEMPLATE_BUCKET" ]; then
  echo "BUILDKITE_DEPLOY_TEMPLATE_BUCKET is not set."
  exit 1
fi

# example
echo "Using S3 bucket: $BUILDKITE_DEPLOY_TEMPLATE_BUCKET"

# copy environment file
#sudo aws s3 cp s3://$BUILDKITE_DEPLOY_TEMPLATE_BUCKET/deploy-template/{FARM}-{REGION}.env \ /usr/local/bin
