name: backstage-validator

on:
  push:
    branches-ignore:
      - "main"

jobs:
  backstage-entity-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: RoadieHQ/backstage-entity-validator@v0.3.2
        with:
          path: 'catalog-info*.yaml'
