name: go-checks

on: [push]

defaults:
  run:
    working-directory: src

jobs:
  go-ensure-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: src/go.mod
          cache: true
          cache-dependency-path: src/go.sum

      - name: Check Go Modules
        run: make ensure-deps

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: src/go.mod

      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          working-directory: src
          args: "-v --timeout=2m"

  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: src/go.mod
          cache: true
          cache-dependency-path: src/go.sum

      - name: Test code
        run: |
          make test-ci
